/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as HoneymoonRouteImport } from './routes/honeymoon'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BookingPackageIdRouteImport } from './routes/booking.$packageId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneymoonRoute = HoneymoonRouteImport.update({
  id: '/honeymoon',
  path: '/honeymoon',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PackagesRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BookingPackageIdRoute = BookingPackageIdRouteImport.update({
  id: '/booking/$packageId',
  path: '/booking/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/family': typeof FamilyRoute
  '/honeymoon': typeof HoneymoonRoute
  '/packages': typeof PackagesRouteWithChildren
  '/visa': typeof VisaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/$packageId': typeof BookingPackageIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$id': typeof PackagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/family': typeof FamilyRoute
  '/honeymoon': typeof HoneymoonRoute
  '/packages': typeof PackagesRouteWithChildren
  '/visa': typeof VisaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/$packageId': typeof BookingPackageIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$id': typeof PackagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/family': typeof FamilyRoute
  '/honeymoon': typeof HoneymoonRoute
  '/packages': typeof PackagesRouteWithChildren
  '/visa': typeof VisaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/$packageId': typeof BookingPackageIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$id': typeof PackagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/family'
    | '/honeymoon'
    | '/packages'
    | '/visa'
    | '/blog/$slug'
    | '/booking/$packageId'
    | '/destinations/$slug'
    | '/packages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/family'
    | '/honeymoon'
    | '/packages'
    | '/visa'
    | '/blog/$slug'
    | '/booking/$packageId'
    | '/destinations/$slug'
    | '/packages/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/family'
    | '/honeymoon'
    | '/packages'
    | '/visa'
    | '/blog/$slug'
    | '/booking/$packageId'
    | '/destinations/$slug'
    | '/packages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FamilyRoute: typeof FamilyRoute
  HoneymoonRoute: typeof HoneymoonRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  VisaRoute: typeof VisaRoute
  BookingPackageIdRoute: typeof BookingPackageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honeymoon': {
      id: '/honeymoon'
      path: '/honeymoon'
      fullPath: '/honeymoon'
      preLoaderRoute: typeof HoneymoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/booking/$packageId': {
      id: '/booking/$packageId'
      path: '/booking/$packageId'
      fullPath: '/booking/$packageId'
      preLoaderRoute: typeof BookingPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PackagesRouteChildren {
  PackagesIdRoute: typeof PackagesIdRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesIdRoute: PackagesIdRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FamilyRoute: FamilyRoute,
  HoneymoonRoute: HoneymoonRoute,
  PackagesRoute: PackagesRouteWithChildren,
  VisaRoute: VisaRoute,
  BookingPackageIdRoute: BookingPackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
